name: CD

on:
  push:
    branches: [main]

jobs:
  cd:
    uses: bamiyanapp/dev-standards/.github/workflows/reusable-cd.yml@v2.4.0
    with:
      semantic_release_node_version: "22"
      enable_shared_release_config: true
      enable_changelog_json: true
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
